[package]
name = "apk-proofs"
version = "0.1.0"
authors = ["Sergey Vasilyev <swasilyev@gmail.com>"]
edition = "2018"
description = "Succinct proofs of a BLS public key being an aggregate key of a subset of signers given a commitment to the set of all signers' keys"
repository = "https://github.com/w3f/apk-proofs"
categories = ["cryptography"]

[dependencies]
ark-ff = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-ec = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra", default-features = false, features = [ "derive" ] }
ark-bls12-377 = { git = "https://github.com/arkworks-rs/curves", default-features = false, features = [ "curve" ] }
ark-bw6-761 = { git = "https://github.com/arkworks-rs/curves", default-features = false }
ark-std = { git = "https://github.com/arkworks-rs/utils", default-features = false }
ark-poly = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-poly-commit = { git = "https://github.com/arkworks-rs/poly-commit", default-features = false }

bitvec = { version = "0.19", default-features = false, features = [ "alloc" ] }
rand = "0.7"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false